version: '3.6'
services:
  postgres:
    image: postgres:12
    volumes:
    - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 5050:80
    volumes:
      - "./docker-volumes/pgadmin:/var/lib/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    depends_on:
    - postgres

  server:
    build: ./server
    environment:
      PORT: 5080
      DATABASE_URL: postgres://test:test@postgres:5432/test
    ports:
      - 4040:80
    volumes:
      - "./server/:/app"
      - /app/node_modules
    depends_on:
      - postgres

  ui:
    build: ./ui
    environment:
      PORT: 80
      CLIENT_GRAPHQL_URL: "http://localhost:4000/v1/graphql"
      SERVER_GRAPHQL_URL: "http://localhost:4000/v1/graphql"
    ports:
      - 3030:80
      - 6006:6006
    volumes:
      - ./ui:/app
      - /app/node_modules